### ISSUE TITLE
Shipyaari - Compliance Check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#105]
### Shipyaari - MytraMoney

context.timestamp in request APIs can't be greater than timestamp in callback response APIs

**/search**
no ttl defined in context
context.transaction id should be a valid uuid
context.timestamp should be in valid rfc3339 format
category and value missing in payload_details

**/on_search**
context.ttl is not required
RTO should be supported in bpp/fulfillments[]
All the available child categories for standard delivery should be provided
Standard Delivery: TAT: P8D??
Doesn't shipyaari support P2P fulfillments?

**/init**
items[] parent_item_id, fulfillment_id and price are invalid keys.
items[].descriptor name, short_desc,long_desc are invalid keys
fulfillments[].tracking is invalid key
contact.email is optional attribute
start and end person.name are not required
tax_number is missing in billing

**/confirm**
PCC should be sent in fulfillments[].start.instructions.short_desc
payment object mismatches in /on_init and /confirm
billing created and updated timestamps can't change in /confirm

**/on_confirm**
fulfillments[].state.descriptor.name is not required

**/on_status**
fulfillments[].tracking can't change in /on_status and /on_confirm
fulfillments[] start and end time.timestamp is missing for fulfillments states "Order-picked-up", "Out-for-delivery", "Order-delivered"

**Comment by prashantpdwivedi** [comment]
@bluecypher 
Thanks for the review.
We will make the required changes

Just some clarification
/on_search
--Standard Delivery: TAT: P8D?? Doesn't shipyaari support P2P fulfillment?  Yes For now we are only supporting P2H2P so that's why the duration is more

/on_status
fulfillments[] start and end time.timestamp is missing for fulfillments states "Order-picked-up", "Out-for-delivery", "Order-delivered"
--We used to refer to the [LSPTESTCASES](https://docs.google.com/spreadsheets/d/1mkAwYJxueOwnlCSyFV6creI53A5_fcOQKtqRiBZWPUI/edit#gid=0&range=C31)
where It is mentioned that the end timestamp is available when the fulfillment state is "Order-Delivered"

So please clarify here

**Comment by prashantpdwivedi** [comment]
@bluecypher 
For the /on_search
**RTO should be supported in bpp/fulfillments[]**
If you refer to my comment in [API contract](https://docs.google.com/document/d/10GpEuKZE2g96DFJT3HKq6wIEMhPC-kkMZhXNn2jHHXc/edit?disco=AAAAqkX50iA)  
It is mentioned by @BLR-0118 that **the RTO quote is a part of /on_search but is added to order value when RTO is initiated**

Also, do we need to pass all the supported options in message.catalog["bpp/fulfillments"] or the one with which we are providing responses with
because as of  now I am passing only options that I am supporting for the current request

**Comment by BLR-0118** [comment]
Logs with VirancInfoTech:
Test Scenario 1:
1. /on_search:
- why is TAT 3 days for shipment between these start & end locations (same pincode). What logic is this based on?
- RTO cost should also be provided in the catalog as per the API contract;
2. /on_confirm:
- AWB# should be sent in /on_update after ready to ship is triggered;
3. Need log for unsolicited /on_cancel and /cancel;

Test Scenario 2:
1. /on_cancel: why is the fulfillment id different from other APIs?

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
@BLR-0118  @bluecypher 
updated logs in verification logs repo [PR](https://github.com/ONDC-Official/verification-logs/pull/599)

**Comment by BLR-0118** [comment]
Test Scenario 1:
1. /on_search:
- difference between search & on_search timestamps is more than 5 secs. Need sub-second search response;
- no RTO quote?
2. /on_confirm:
- difference between confirm & on_confirm timestamps is more than 8 secs. This won't work;
3. /on_update:
- in response to "ready to ship", LSP is required to send the pickup time range (fulfillment.start.time.range.start & end);
- not sure where shipping label is being shared?

Pls resubmit logs only for scenario 1, also including unsolicited on_cancel

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
@BLR-0118 
I think there is some confusion 
Please refer to the latest logs I have submitted on the verification logs repo named [Shipyaari-ViranInfotech](https://github.com/ONDC-Official/verification-logs/tree/main/logs/Shipyaari/Shipyaari-VirancInfotech)

**Comment by BLR-0118** [comment]
Checked above logs. Need clarification on the following:
1. /confirm & /on_confirm - diff in Context.timestamp > 5 secs. Why?
2. /on_update:
- LSP is supposed to send shipping label for inter-city shipments (I'm assuming from the TAT & P2H2P that this will be inter-city, though the start & end pin codes are the same);

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
@BLR-0118 
Updated the logs for the Logistics Test Scenario 1 as per the review [PR](https://github.com/ONDC-Official/verification-logs/pull/630)

Kindly review!

**Comment by BLR-0118** [comment]
1. /on_confirm:
- difference in timestamp between this & /confirm is close to 5 secs. Why?
- order.created_at has changed from what's in /confirm;
2. billing.created_at & updated_at changes between /init (where originally set) and /on_status APIs. Why?

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
I will update the logs for
order.created_at has changed from what's in /confirm;
billing.created_at & updated_at changes between /init (where originally set) and /on_status APIs. Why?

but for **difference in timestamp between this & /confirm is close to 5 secs. Why?**
As our system internally takes about this time to create the consignment as you know we are a dedicated provider and an aggregator so internal processes take about this amount of time to create the consignment
so right now we are unable to do anything to reduce the response

so can you please provide any alternative solution for this or can we proceed with this?
@BLR-0118  @bluecypher

**Comment by prashantpdwivedi** [comment]
@BLR-0118 @bluecypher 
I have updated the logs [UpdatedLogs](https://github.com/ONDC-Official/verification-logs/pull/655)
Kindly Review

awaiting for a reply Related to the /confirm and /on_confirm timestamp

**Comment by BLR-0118** [comment]
1. /on_search:
- TAT given for category "Standard Delivery" is 11 days (P11D)..checking if this is intended?
2. related to /confirm & /on_confirm: what happens during consignment creation - does it only create the manifest or also creates task for allocating agent? Can't this be optimized for better performance?
No need to resubmit logs but let's resolve the above 2 issues.

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
@BLR-0118 
1. for the TAT right now it is using development server API so that's why it is showing days a bit higher on LIVE environment it will work fine.
 2. Internally we create the consignment (i.e the consignment is getting assigned to a particular agent so that's why the response time is that much between 5 to 6 seconds) we have already shifted our server to a new server as the response time has been reduced to this... but right now we are not able to do anything to reduce the response time lower than this...
Awaiting for your response...

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
No, It's not directly assigned to the agent 
Internally we get the pickup date which will be mostly the next date or the day after that (It is based on various criteria like pin codes, location, and all)
So before proceeding for pickup the agent will first confirm whether the order is ready for pickup and then pickup will be initiated that our flow currently
@BLR-0118

**Comment by prashantpdwivedi** [comment]
@BLR-0118 
We have handled the response time issue for the confirm call
Kindly update for further steps
If it require to resubmit the logs from our end then please let me know so I can do the same

**Comment by prashantpdwivedi** [comment]
We had decided to revert to the confirm API immediately and then go for the consignment creation as currently, on_confirm API specs do not require any data related to consignment as per my understanding, correct me if I am wrong here.
But then after a discussion with CS Prabhakar sir, we decided to go for the consignment creation (i.e. actually placing the order) in the /update call thereby resulting in handling the partial cancellation if any at our end.

But in the /on_update API it required data like awb_no which can only be get at our end after the consignment gets created so we are now working on reducing the response time of the in-house APIs so that our middleware /update API response time can also be reduced 

Apart from this, I had a question
as the amount for the Logistics order will get paid to the user in the confirm call only
so e.g. BPP is charging 30Rs for a package
and the user paid it during the confirm-on_confirm process, now if there is any partial cancellation then there might be a chance that the amount may get reduced or increased so how to handle that scenario?
where will the updated price be passed and how the settlement process takes place based on that?

**Comment by prashantpdwivedi** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
not sure what's the partial cancellation at your end? Pls elaborate

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
@BLR-0118 
I am considering that
the update call is the final call which contains the ready_to_ship trigger and can also contain changes in the package payload due to partial cancellation 
earlier we were not supporting the update of the package details as we used to create the consignment in the confirm call itself. Now we will create the consignment in the update call thereby handling the update package detail (due to partial cancellation) can also be handled
Hope this answers the questions
Also please answer the question asked above in the previous comment [link](https://github.com/ONDC-Official/v1.1.0-logs/issues/105#issuecomment-1545188701)

**Comment by BLR-0118** [comment]
Logistics Test Scenario 1
================
1. /confirm:
- for intercity shipment, PCC is the shipping label, don't need separate confirmation code

2. /on_status (order picked up):
- time for pickup should be recorded (fulfillment.start.time.timestamp)

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
@BLR-0118 
1. for intercity shipment, PCC is the shipping label, don't need a separate confirmation code 
- It will get handled by the seller's side 
2. Time for pickup should be recorded (fulfillment.start.time.timestamp)
- It is there Kindly check [HERE](https://github.com/ONDC-Official/verification-logs/blob/main/logs/Shipyaari/Shipyaari-VirancInfotech/Logistics-Test-Scenario-1/Unsolicitated%20Status%20Calls/on_status_OPU.json#L48)

Kindly review

**Comment by BLR-0118** [comment]
@prashantpdwivedi

**Comment by prashantpdwivedi** [comment]
Thank you @BLR-0118
