### ISSUE TITLE
Qaddoo - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#208]
All the 5 flows should be shared as per the [test case scenarios](https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit)

Following payloads must be present in the logs

1. search by item with on_search response
2. /update API for refund calculation (wherever applicable)

@rajeevrawat982

**Comment by rajeevrawat982** [comment]
@bluecypher 

We are caching stores by making search calls based on the city and using that cached results for product search instead of doing real time search on the network. Whenever our user enters the store we make a search call again to a specific BPP to get a new transaction_id for proceeding further. Do you still want us to make a realtime search call on network whenever a user tries to search for a product?

**Comment by bluecypher** [comment]
Yes, search by item is mandatory for tech clearance. 

@rajeevrawat982

**Comment by bluecypher** [comment]
@rajeevrawat982, please resubmit the logs, the recent PR created a conflict.

**Comment by rajeevrawat982** [comment]
@bluecypher Done created a new PR

**Comment by abhinavv245** [comment]
## Flow 1

- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

**/search**
- '@ondc/org/buyer_app_finder_fee_type' must be equal to 'percent' instead of "Percent"

**/init**
- /context must have required property 'ttl'
- billing.created_at should match context.timestamp
- billing.updated_at should match context.timestamp
- items/fulfillment_id mismatches in /on_select and /init 

**/confirm**
- /context must have required property 'ttl'
- Billing object mismatches in /init and /confirm
(created_at and updated_at timestamps are different)
- fulfillments.end.person object is missing
- order.created_at timestamp should match context.timestamp
- order.updated_at timestamp should match order.created_at timestamp

**/update**
- /context must have required property 'ttl'

**/update(with payment)**
- /payment/settlement_timestamp cannot be greater than context.timestamp


## Flow 2

- similar issues as Flow 1
- /on_search response missing 

## Flow 3, Flow 4, Flow 5

- similar issues as Flow 1

@rajeevrawat982

**Comment by abhinavv245** [comment]
## Flow 1

**/select**

- /message/order/items must have required property 'location_id'

**/init**

- In /fulfillments, id '1' does not exist in /on_select
(should be mapped correctly)

**/confirm**

- '@ondc/org/title_type' in quote.breakup must be equal to one of the allowed values (item,delivery,packing,tax,misc,discount)
- '@ondc/org/buyer_app_finder_fee_type' must be equal to 'percent' (instead of 'Percent')

## Flow 2

**/on_cancel (unsolicited)**

- empty payload

## Flow 3, Flow 4, Flow 5

- similar issues as Flow 1

**Comment by rajeevrawat982** [comment]
@abhinavv245 new PR is raised with updated flows

**Comment by BLR-0118** [comment]
Flow 1
====
1. /init:
- address.name + address.building + address.locality should be less than 190 chars;
- why is building = locality?
- phone no is invalid (no "+");
2. /on_status_unsolicited_order_complete:
- pickup time (fulfillment.start.time.timestamp) seems invalid. Why was this not NACK'd?

**Comment by bluecypher** [comment]
## Flow 1

- why does the gps location change in /search and /select
- /update (for refund settlement) is an FYI call; no callback is required

## Flow 4

**/on_status (Order-picked-up)**

- /fulfillments/0/end must have required property 'time' (BAP must repond with a NACK)

## Flow 5

- test scenaio must include complete out-of-stock for one of the items


@rajeevrawat982

**Comment by rajeevrawat982** [comment]
@bluecypher   
Flow 1 
we tried to kept the same pincode only. I will submit this flow again with same gps as well.

Flow 4 
We have this validation at place but it's difficult to figure out seller who return fully expected results because of that we gave flexibility to few hard checks.  

Flow 5 
I will be submit again .

**Comment by bluecypher** [comment]
**/on_search**

- statutory_reqs_packaged_commodities must have required property 'imported_product_country_of_origin'; Buyer app must respond with a NACK

**/on_update (Return_Delivered)**

- message_id of all unsolicited /on_update calls should be same to track that particular /update (return) request; Buyer app needs to handle this


@rajeevrawat982, Please resubmit logs for Flow 1

**Comment by bluecypher** [comment]
@BLR-0118, the Qaddoo Buyer App (v1.1.0) logs seem fine. Please proceed with your review.

@rajeevrawat982
