### ISSUE TITLE
eSamudaay - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.1.0-logs#24]
Flow 1:
1. /on_search:
- provider.time.timestamp for "enable" should exactly match Context.timestamp;
- for grocery commodities, pls use category_id from this list [here](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0) and not any of the deprecated category_ids;
2. /on_init:
- why is billing.updated_at timestamp different from billing.created_at? Both are maintained by the buyer app;
3. /on_confirm:
- order.updated_at should be updated to Context.timestamp since default fulfillment state added;
4. For all APIs:
- billing.created_at, updated_at should be the same as what was sent in /init unless the buyer app subsequently changes billing info through /update;
- order.created_at should be the same as what was sent in /confirm but order.updated_at has to be updated in all callback APIs where updates are made to order state;
Logs need to be submitted for flows 3 & 4 as well.

**Comment by BLR-0118** [comment]
@ShishirPrashanth

**Comment by ShishirPrashanth** [comment]
Fixed in https://github.com/ONDC-Official/v1.1.0-logs/pull/41:
1a. fixed
1b. fixed (fix pushed to production already and merchants have been informed to upgrade to new taxonomy, this will be wip until fully migrated in prod)

2. fixed

3. fixed

4a. fixed
4b. fixed

Logs for flow 3 and 4 are not applicable for the following reasons:
Flow 3: Return rejected is not supported at eSamudaay. Any return request will immediately move to Liquidated state.
Flow 4: eSamudaay doesn't maintain stock count for inventory. Items are either in stock or out of stock. Out of stock scenario (quantity = 0) case has been submitted in flow 5.

@BLR-0118

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- item.descriptor.code should comply with the format in API contract;
- contact_details_consumer_care should comply with the format in API contract ("name,email,contact no");
2. /on_init:
- fulfillment.end.person.name comes from buyer app in /confirm, can't appear here;

Flow 2
====
1. /on_select: non-serviceable means there are no fulfillment related charges i.e. for delivery, packing, etc. (those can be removed)

**Comment by BLR-0118** [comment]
@ShishirPrashanth

**Comment by ShishirPrashanth** [comment]
Fixed in https://github.com/ONDC-Official/v1.1.0-logs/pull/64

Flow 1:
1a. FIX: removed item.descriptor.code since it is optional
1b. fixed

2b. FIX: removed fulfillment.end.person from on_init

Flow 2:
1. Fixed (no charges sent for non serviceable)

**Comment by ShishirPrashanth** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- serviceability construct: can't use category of "PACKAGED_FOODS" (invalid) or "Packaged Commodities" (deprecated). Same applies to item.category_id;
- item.parent_item_id will be used for variants. What's it being used here for and if not used correctly, should be removed;

**Comment by BLR-0118** [comment]
@ShishirPrashanth

**Comment by ShishirPrashanth** [comment]
@BLR-0118 
1a. All invalid categories have been deleted from prod. In preprod due to some testing they may have crept up. As discussed, deprecated categories are being removed in prod. This is a time consuming manual process and has already been done for most products..

1b. We are using item.parent_item_id for variants. With current implementation Aashirvaad Atta 5kg and Aashirvaad Atta 1kg will have same parent item id (aashirvaad atta) and different item ids. With categories like Fashion this will be more useful.

**Comment by BLR-0118** [comment]
logs cleared for v1.1.0
