### ISSUE TITLE
iThink Logistics - compliance check

### ISSUE THREAD

**Issue by tanya-ondc** [ONDC-Official/v1.1.0-logs#296]
## Delivered Flow

**/on_confirm**
  {
    instancePath: '/on_confirm/message/order/fulfillments/0/type',
    message: { allowedValue: 'Prepaid' } - Must match value in /confirm.
  }

**/update**

  {
    instancePath: '/update/message/order/fulfillments/0/end/instructions',
    message: "must have required property 'additional_desc'"
  },
  {
    instancePath: '/update/message/order/fulfillments/',
    message: 'Fulfillment object should include start and end instructions if ready_to_ship is Yes'
  },
  }

** Same issues in Cancellation FLow**

@shubhamdepasser

**Comment by shubhamdepasser** [comment]
We have completed the instructions as mentioned above in our code and tested with Viranc Infotech and raised the below-mentioned PR with a new log. https://github.com/ONDC-Official/v1.1.0-logs/pull/304

**Comment by abhinavv245** [comment]
## Delivered Flow

- Timestamp difference between /action and /on_action api should be less than 1 sec

**/on_search**

- Item TAT timestamp (/items/time/timestamp) for 'Next Day Delivery' should be for the next day (date) (context.timestamp plus item level TAT should not exceed the next day)
- the approx distance between start and end location is 4km and the shipment is P2H2P, is this intentional? (otherwise realistic pincodes should be provided)
- For P2H2P shipments, dimensions are required in @ondc/org/payload_details in search request (LSP should send a NACK in case they are not provided)
- The price for a next day delivery and approx distance of 4km is around 885INR and more (realistic prices should be provided)

**/on_update**

- start time range should be accurately recorded
- end time range is required in case ready to ship = yes

**/on_status**

- fulfillment/type should not change (Prepaid)
- /message/order/fulfillments/ must have required property 'start'
- /message/order/fulfillments/ must have required property 'end'
- order created_at and updated_at timestamps should be provided

**/on_status (Order-picked-up and Out for delivery)**

- similar issues as /on_status
- pickup (fulfillments/start/time/timestamp) timestamp is missing

**/on_status (Order-delivered)**

- similar issues as /on_status
- delivery (fulfillments/end/time/timestamp)timestamp is missing

## Cancelled Flow

- similar issues as above

**/on_cancel**

- unsolicited /on_cancel flow should be provided with approproate cancellation_reason_id

@shubhamdepasser

**Comment by abhinavv245** [comment]
## Delivered Flow 

**/on_search**

- time/duration of more than 24 hours should be converted to days
- Item TAT timestamp should have the date for the next day w.r.t context timestamp for category 'Next Day Delivery'

**/on_status**

- Order has not been accepted even after one hour of order confirmation (Is this intentional) 
- @ondc/org/ewaybillno and @ondc/org/ebnexpirydate cannot change in /on_status

## Canceled Flow

- similar issues as above

@shubhamdepasser

**Comment by abhinavv245** [comment]
## Delivered Flow

**/on_search**

- /message/catalog/bpp/providers/items/time/timestamp should be in RFC 3339 UTC format (YYYY-MM-DDTHH:MM:SS.MSSZ) (incorrect: 2023-07-12T14:30:000.000Z)

**/on_confirm**

- @ondc/org/ewaybillno and @ondc/org/ebnexpirydate should be provided for P2H2P shipments in /on_confirm or /on_update
- fulfillments/@ondc/org/awb_no should not have more than 16 characters

**/on_update**

- delivery instructions are not required in /on_update

**/on_status**

- pickup date (fulfillments/start/time/timestamp) is even before the order date
- start and end time range should be in RFC 3339 UTC format (YYYY-MM-DDTHH:MM:SS.MSSZ)
 (incorrect: 2023-07-11T9:30:000.000Z)

## Cancelation Flow

- similar issues as above 

## Flow 1

**/on_confirm**

- created_at, updated_at mismatches in /billing in /init and /on_confirm

## Flow 2

**/on_cancel**

- for cancellation_reason_id - 011 (Buyer not found or cannot be contacted), RTO should be initiated and RTO delivered/disposed should be supported

@shubhamdepasser

**Comment by abhinavv245** [comment]
## Flow 1 and Flow 2

**/on_status**

- start and end /time/range/start should be in RFC 3339 UTC format (YYYY-MM-DDTHH:MM:SS.MSSZ, incorrect: 2023-07-25T9:30:00.000Z)

**/track**

- /track is only applicable for hyperlocal Immediate Deliveries

### Ques: Is RTO supported with all the possible states?

@shubhamdepasser

**Comment by shubhamdepasser** [comment]
/track is only applicable for hyperlocal Immediate Deliveries.
-(We are giving tracking details to Standard Delivery, Express Delivery, Same Day Delivery, Next Day Delivery also).

Ques: Is RTO supported with all the possible states? 
- We are supported RTO for all states except Completed state.

**Comment by abhinavv245** [comment]
@shubhamdepasser For RTO, I meant if RTO Initiated, Delivered, Disposed are supported?

**Comment by shubhamdepasser** [comment]
@abhinavv245 Yes

**Comment by shubhamdepasser** [comment]
@abhinavv245 
We have uploaded the resolved log Please give your valuable feedback.

**Comment by bluecypher** [comment]
Invalid Catalog; Payload should contain aggregate information rather than individual provider catalogs.

@shubhamdepasser

**Comment by shubhamdepasser** [comment]
@abhinavv245 We have uploaded resolved logs in last few days please give your valuable feedback.

**Comment by bluecypher** [comment]
**on_status**

- agent consignment related states must be sent as part of unsolicited calls

**/on_confirm**

- optional attributes @ondc/org/ewaybillno, @ondc/org/ebnexpirydate can't be empty

**on_cancel**

- context/timestamp can't be the same as /on_confirm timestamp

**/on_track**

- Is live tracking supported for Grocery category?


@shubhamdepasser, Please provide RTO flow as well.

**Comment by shubhamdepasser** [comment]
**Point 1:**
on_status
agent consignment related states must be sent as part of unsolicited calls

**iThink feedback-**
- We are providing Standard Delivery and Express Delivery (Same Day Delivery, Next Day Delivery). But as of now we don't provide hyperlocal delivery so we are not providing agent consignment related states like (Searching-for-Agent, Agent-assigned).

**Point 2:**
on_confirm
optional attributes @ondc/org/ewaybillno, @ondc/org/ebnexpirydate can't be empty

**iThink feedback-**
- According to Logistics Consensus, if the value of the shipment is more than 50000 then we will get the ewaybill number and expiry date from the sellers but in this case the shipment value is less than 50000 so we have not received the ewaybill number and expiry date from the seller.

**Point 3:**
on_cancel
context/timestamp can't be the same as /on_confirm timestamp.

**iThink feedback-**
-We checked our logs, in that the Flow1 /on_confirm timestamp **2023-08-17T05:05:50.457Z** and order /on_cancel timestamp **2023-08-17T06:16:42.494Z**. and for the Flow2 /on_confirm timestamp **2023-08-17T05:11:02.853Z** and order /on_cancel timestamp **2023-08-17T06:19:24.029Z**, both on_confirm and on_cancel timestamp are different.

**Point 4:**
/on_track
Is live tracking supported for Grocery category?

**iThink feedback-**
As per delivery boy marks status on fields like (pickup, out for delivery, delivered etc.), at the same time we get it on webhook and we update order status in our panel so seller and buyer can track real time order status on below link.
URL - https://www.ithinklogistics.co.in/postship/tracking/XSE20012937660001

@bluecypher @abhinavv245

**Comment by shubhamdepasser** [comment]
RTO flow is uploaded - https://github.com/ONDC-Official/v1.1.0-logs/tree/main/iThink_Logistics_ONDC_preprod/Testing%201%20-%20Viranc%20Infotech/Cancelation_Flow/RTO

**Comment by bluecypher** [comment]
**/on_status (RTO)**
- fulfillments/type should be "Prepaid" (in uppercase) for forward shipment
- to process RTO delivery, the enum must be 'RTO-Delivered' in /fulfillments (type="RTO")

@shubhamdepasser

**Comment by bluecypher** [comment]
## Delivered Flow

**/on_status**

- pickup time (fulfillments/start/time/timestamp) is missing for fulfillment state - Order-delivered

## Cancellation Flow (RTO)

**/on_status**

- context/timestamp should be in RFC 3339 UTC time format for fulfillment state - Pending
- tracking must be boolean for fulfillment type RTO (RTO-Initiated)
- RTO Pickup (fulfillments/start/time/timestamp) time is missing for fulfillment state - RTO-Initiated

@shubhamdepasser

**Comment by bluecypher** [comment]
**/on_status (Order-picked-up)**
- unsolicited call should be initiated for Order-picked-up state

**/on_status (Out-for-delivery / Order-delivered)**
- pickup timestamp is not captured correctly; should be the same as in Order-picked-up state


@shubhamdepasser

**Comment by bluecypher** [comment]
@BLR-0118, the iThink Logistics (LSP) logs seem fine. Please proceed with your review.

@shubhamdepasser

**Comment by shubhamdepasser** [comment]
@BLR-0118 Please share your valuable feedback.
