### ISSUE TITLE
Snapbizz (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#468]
**/on_receiver_recon**

- context/domain should be ONDC:NTS10
- context/timestamp can't be the same as in /receiver_recon
- context/action should be on_receiver_recon

**Correction Flow**

- Counterparty_recon_status is 03 (Underpaid); Why is the counterparty_diff_amount null? 

@anandsn007

**Comment by bluecypher** [comment]
- receiver_recon_failed is not a valid scenario. 
- timestamps can't be future dated.
- When sending the /on_receiver_recon, the order_recon_status should not be 03 (Deemed Settled); it should be 02 (Final) instead.
- correction flow through IGM is not a part of MVP

#### Resubmit the APIs as per the test case scenarios.

@anandsn007

**Comment by bluecypher** [comment]
### /receiver_recon

- settlement timestamp can't be the same as context/timestamp;
- settlement counterparty can't be "Buyer"; should be a valid network participant
- @ondc/org/buyer_app_finder_fee_type: enum should be "percent"
- payment_type: enum should be "ON-ORDER"
- order/state: enum should be "Completed"

**Successful Recon**

- orderbook was created on 04/08/2023 and amount was settled on 21/08/2023. The entire settlement cycle is going beyond the defined ttl; How is it handled?
- deduction by collector is higher than the buyer app finder fee; Why isn't it covered in correction flow?

**Correction Flow**

- order ID can't be repeated for 2 different orders between the same collector-receiver pair

@anandsn007

**Comment by bluecypher** [comment]
@anandsn007, all the previously identified issues should be resolved.

**Comment by anandsn007** [comment]
/receiver_recon
1. settlement timestamp can't be the same as context/timestamp; -- FIXED
2. settlement counterparty can't be "Buyer"; should be a valid network participant -- FIXED
3. @ondc/org/buyer_app_finder_fee_type: enum should be "percent". There was no issue, it is percent only, please check again
4. payment_type: enum should be "ON-ORDER" -- *FIXED*
5. order/state: enum should be "Completed" -- *FIXED*

Successful Recon
1. orderbook was created on 04/08/2023 and amount was settled on 21/08/2023. The entire settlement cycle is going beyond the defined ttl; How is it handled? -- Submitted logs with fresh recond for fresh orders in the files

2. deduction by collector is higher than the buyer app finder fee; Why isn't it covered in correction flow? - Not sure here what are you talking, as deduction by collector will always be higher than buyer app finder fee, because it will include the gst on buyer app finder fee

Correction Flow
order ID can't be repeated for 2 different orders between the same collector-receiver pair --FIXED

**Comment by anandsn007** [comment]
/on_receiver_recon

context/domain should be ONDC:NTS10 -- FIXED
context/timestamp can't be the same as in /receiver_recon -- FIXED
context/action should be on_receiver_recon -- FIXED
Correction Flow

Counterparty_recon_status is 03 (Underpaid); Why is the counterparty_diff_amount null? -- FIXED


receiver_recon_failed is not a valid scenario. -- Removed this
timestamps can't be future dated. -- Fixed in the new log submitted
When sending the /on_receiver_recon, the order_recon_status should not be 03 (Deemed Settled); it should be 02 (Final) instead. -- Fixed
correction flow through IGM is not a part of MVP -- NA

**Comment by bluecypher** [comment]
**/receiver_recon**

Missing Mandatory Properties:

- /message/orderbook/orders/0/payment must have required property '@ondc/org/buyer_app_finder_fee_type'
- /message/orderbook/orders/0/payment/@ondc/org/settlement_details/0 must have required property 'beneficiary_name'

@anandsn007

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0

@anandsn007
