### ISSUE TITLE
Ola (BAP) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.1.0-logs#651]
## Flow 1

**/update (Refund FYI call)**

- use update_target as "item" for now
- netbanking is not a valid enum for settlement type in "@ondc/org/settlement_details" (use neft, rtgs, upi)

## Flow 2, 4, 5

**/select**

- context/transaction_id can't change for Non-serviceable/OOS scenarios

## Flow 4

**/update**

- FYI update call is missing after the refund triggering state (Liquidated)

@Anoopsmohan

**Comment by Anoopsmohan** [comment]
@bluecypher reported issues have been fixed. Please review it again.
PRs:
https://github.com/ONDC-Official/v1.1.0-logs/pull/663
https://github.com/ONDC-Official/v1.1.0-logs/pull/659

**Comment by bluecypher** [comment]
Clarifications:

- why is the GPS changing in the /search and /select call for live search?
- door should be an optional attribute in /billing and /fulfillments
- why is the payment/params/transaction_id same as context/transaction_id in /confirm

## Flow 4

- invalid calculation of settlement_amount; should have a decimal precision of upto 2 digits


@Anoopsmohan

**Comment by Anoopsmohan** [comment]
@bluecypher 

[1] Please ignore the search and on_search files, as we are **not doing any live searches**. We are doing a city search and caching the catalog. Since we are not able to use the utility, without these files, we manually added it in the folder. 
[2] Since it is an option field, we can still send it in the request, right? Or do you want us to remove this attribute from "billing" and "fulfillment"? please confirm.
[3] it's a bug. We are fixing it.

Flow 4: We are fixing it.

**Comment by Anoopsmohan** [comment]
@bluecypher 
Issues [3] & [4] have been fixed. Kindly merge and review.
PR: https://github.com/ONDC-Official/v1.1.0-logs/pull/672

**Comment by bluecypher** [comment]
@BLR-0118, the Ola Buyer App v1.1.0 logs seem fine. Please proceed with your review.

@Anoopsmohan
